In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/spaceship-titanic/sample_submission.csv
/kaggle/input/spaceship-titanic/train.csv
/kaggle/input/spaceship-titanic/test.csv

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
sns.set(style='darkgrid', font_scale=1.4)
from imblearn.over_sampling import SMOTE
import itertools
import warnings
warnings.filterwarnings('ignore')
import plotly.express as px
import time

In [3]:
train = pd.read_csv('/kaggle/input/spaceship-titanic/train.csv')
test = pd.read_csv('/kaggle/input/spaceship-titanic/test.csv')
ss = pd.read_csv('/kaggle/input/spaceship-titanic/sample_submission.csv')

In [4]:
ss

     PassengerId  Transported
0        0013_01        False
1        0018_01        False
2        0019_01        False
3        0021_01        False
4        0023_01        False
...          ...          ...
4272     9266_02        False
4273     9269_01        False
4274     9271_01        False
4275     9273_01        False
4276     9277_01        False

[4277 rows x 2 columns]

In [6]:
train.columns = [x.lower() for x in train.columns]
test.columns = [x.lower() for x in test.columns]

In [7]:
train.head()

,passengerid,homeplanet,cryosleep,cabin,destination,age,vip,roomservice,foodcourt,shoppingmall,spa,vrdeck,name,transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True

In [8]:
def get_unique_values(original_data, num_unique_values = 10): 
    '''
    This function return a DataFrame of variables names and their unique values.
    original_data = main dataframe 
    num_unique_values = number of unique values not more than given
    '''
    pd.set_option('display.max_colwidth', None)
    # Create a list to store the unique values
    unique_values_list = []

    # Iterate through the columns of the original dataset
    for column_name in original_data.columns:
        
        if len(original_data[column_name].unique()) <= num_unique_values:
            unique_values = original_data[column_name].unique() 

            # Convert unique values to a comma-separated string
            unique_values_str = ', '.join(map(str, unique_values))

            unique_values_list.append({'Variable': column_name, 'Unique_Values': unique_values_str})

    # Create a new DataFrame from the list of dictionaries
    unique_values_df = pd.DataFrame(unique_values_list)
    return unique_values_df

In [9]:
get_unique_values(train)

      Variable                                 Unique_Values
0   homeplanet                      Europa, Earth, Mars, nan
1    cryosleep                              False, True, nan
2  destination  TRAPPIST-1e, PSO J318.5-22, 55 Cancri e, nan
3          vip                              False, True, nan
4  transported                                   False, True

In [ ]:
train.info()

In [ ]:
train.isnull().sum()

In [ ]:
total_missing = train.isnull().sum().sum()
total_cells = np.product(train.shape)


percent_missing = round((total_missing/total_cells) * 100)
print('data missing:',percent_missing,"%")