In [3]:
!pip install bar_chart_race
import pandas as pd
import bar_chart_race as bcr

Collecting bar_chart_race
  Downloading bar_chart_race-0.1.0-py3-none-any.whl (156 kB)
     |████████████████████████████████| 156 kB 4.2 MB/s
Requirement already satisfied: matplotlib>=3.1 in /opt/conda/lib/python3.7/site-packages (from bar_chart_race) (3.5.0)
Requirement already satisfied: pandas>=0.24 in /opt/conda/lib/python3.7/site-packages (from bar_chart_race) (1.3.4)
Requirement already satisfied: pyparsing>=2.2.1 in /opt/conda/lib/python3.7/site-packages (from matplotlib>=3.1->bar_chart_race) (3.0.6)
Requirement already satisfied: python-dateutil>=2.7 in /opt/conda/lib/python3.7/site-packages (from matplotlib>=3.1->bar_chart_race) (2.8.0)
Requirement already satisfied: pillow>=6.2.0 in /opt/conda/lib/python3.7/site-packages (from matplotlib>=3.1->bar_chart_race) (8.2.0)
Requirement already satisfied: setuptools-scm>=4 in /opt/conda/lib/python3.7/site-packages (from matplotlib>=3.1->bar_chart_race) (6.3.2)
Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.7/site-packages (from matplotlib>=3.1->bar_chart_race) (0.11.0)
Requirement already satisfied: numpy>=1.17 in /opt/conda/lib/python3.7/site-packages (from matplotlib>=3.1->bar_chart_race) (1.19.5)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.7/site-packages (from matplotlib>=3.1->bar_chart_race) (21.0)
Requirement already satisfied: fonttools>=4.22.0 in /opt/conda/lib/python3.7/site-packages (from matplotlib>=3.1->bar_chart_race) (4.28.2)
Requirement already satisfied: kiwisolver>=1.0.1 in /opt/conda/lib/python3.7/site-packages (from matplotlib>=3.1->bar_chart_race) (1.3.2)
Requirement already satisfied: pytz>=2017.3 in /opt/conda/lib/python3.7/site-packages (from pandas>=0.24->bar_chart_race) (2021.3)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.7/site-packages (from python-dateutil>=2.7->matplotlib>=3.1->bar_chart_race) (1.16.0)
Requirement already satisfied: setuptools in /opt/conda/lib/python3.7/site-packages (from setuptools-scm>=4->matplotlib>=3.1->bar_chart_race) (59.1.1)
Requirement already satisfied: tomli>=1.0.0 in /opt/conda/lib/python3.7/site-packages (from setuptools-scm>=4->matplotlib>=3.1->bar_chart_race) (1.2.2)
Installing collected packages: bar-chart-race
Successfully installed bar-chart-race-0.1.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

SyntaxError: invalid syntax (2350361319.py, line 1)

In [4]:
df = pd.read_csv("https://gist.githubusercontent.com/lorenzofelletti/36df65f62e927108b628614030a25cda/raw/5f225d6c857b5c295713d3b707ee81607f10d0d0/motogp-2020-championship-standing.csv")

In [5]:
df.head()

,race,Joan Mir,Franco Morbidelli,Alex Rins,Andrea Dovizioso,Pol Espargaro,Maverick Vinales,Jack Miller,Fabio Quartararo,Miguel Oliveira,...,Aleix Espargaro,Cal Crutchlow,Stefan Bradl,Iker Lecuona,Bradley Smith,Esteve Rabat,Michele Pirro,Mika Kallio,Lorenzo Savadori,Marc Marquez
0,race 1,0,11,0,16,10,20,13,25,8,...,0,0,0,0,1,2,0,0,0,0
1,race 2,11,11,6,26,19,40,13,50,8,...,0,3,0,0,5,7,0,0,0,0
2,race 3,11,31,19,31,19,42,20,59,18,...,6,6,0,0,5,7,0,0,0,0
3,race 4,31,31,19,56,19,48,36,67,18,...,11,7,0,7,8,7,4,0,0,0
4,race 5,44,32,29,67,35,48,56,70,43,...,15,7,0,13,8,7,4,0,0,0

In [8]:
df = df.set_index('race')

In [9]:
df.head()

,Joan Mir,Franco Morbidelli,Alex Rins,Andrea Dovizioso,Pol Espargaro,Maverick Vinales,Jack Miller,Fabio Quartararo,Miguel Oliveira,Takaaki Nakagami,...,Aleix Espargaro,Cal Crutchlow,Stefan Bradl,Iker Lecuona,Bradley Smith,Esteve Rabat,Michele Pirro,Mika Kallio,Lorenzo Savadori,Marc Marquez
race,,,,,,,,,,,,,,,,,,,,,
race 1,0,11,0,16,10,20,13,25,8,6,...,0,0,0,0,1,2,0,0,0,0
race 2,11,11,6,26,19,40,13,50,8,19,...,0,3,0,0,5,7,0,0,0,0
race 3,11,31,19,31,19,42,20,59,18,27,...,6,6,0,0,5,7,0,0,0,0
race 4,31,31,19,56,19,48,36,67,18,37,...,11,7,0,7,8,7,4,0,0,0
race 5,44,32,29,67,35,48,56,70,43,46,...,15,7,0,13,8,7,4,0,0,0

In [1]:
bcr.bar_chart_race(df=df, title="2020 MotoGP Championship", orientation='h', sort='desc', n_bars=10, steps_per_period=40, period_length=2000)

NameError: name 'bcr' is not defined