In [8]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/customer-satisfaction-in-airline/Invistico_Airline.csv

In [54]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_row', None)

In [23]:
df = pd.read_csv("/kaggle/input/customer-satisfaction-in-airline/Invistico_Airline.csv")
df.head()

,satisfaction,Customer Type,Age,Type of Travel,Class,Flight Distance,Seat comfort,Departure/Arrival time convenient,Food and drink,Gate location,Inflight wifi service,Inflight entertainment,Online support,Ease of Online booking,On-board service,Leg room service,Baggage handling,Checkin service,Cleanliness,Online boarding,Departure Delay in Minutes,Arrival Delay in Minutes
0,satisfied,Loyal Customer,65,Personal Travel,Eco,265,0,0,0,2,2,4,2,3,3,0,3,5,3,2,0,0.0
1,satisfied,Loyal Customer,47,Personal Travel,Business,2464,0,0,0,3,0,2,2,3,4,4,4,2,3,2,310,305.0
2,satisfied,Loyal Customer,15,Personal Travel,Eco,2138,0,0,0,3,2,0,2,2,3,3,4,4,4,2,0,0.0
3,satisfied,Loyal Customer,60,Personal Travel,Eco,623,0,0,0,3,3,4,3,1,1,0,1,4,1,3,0,0.0
4,satisfied,Loyal Customer,70,Personal Travel,Eco,354,0,0,0,3,4,3,4,2,2,0,2,4,2,5,0,0.0

In [29]:
df.describe()

,Age,Flight Distance,Seat comfort,Departure/Arrival time convenient,Food and drink,Gate location,Inflight wifi service,Inflight entertainment,Online support,Ease of Online booking,On-board service,Leg room service,Baggage handling,Checkin service,Cleanliness,Online boarding,Departure Delay in Minutes,Arrival Delay in Minutes
count,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129487.000000
mean,39.427957,1981.409055,2.838597,2.990645,2.851994,2.990422,3.249130,3.383477,3.519703,3.472105,3.465075,3.485902,3.695673,3.340807,3.705759,3.352587,14.713713,15.091129
std,15.119360,1027.115606,1.392983,1.527224,1.443729,1.305970,1.318818,1.346059,1.306511,1.305560,1.270836,1.292226,1.156483,1.260582,1.151774,1.298715,38.071126,38.465650
min,7.000000,50.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,27.000000,1359.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,3.000000,2.000000,3.000000,2.000000,3.000000,3.000000,3.000000,2.000000,0.000000,0.000000
50%,40.000000,1925.000000,3.000000,3.000000,3.000000,3.000000,3.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,3.000000,4.000000,4.000000,0.000000,0.000000
75%,51.000000,2544.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,5.000000,5.000000,4.000000,5.000000,5.000000,4.000000,5.000000,4.000000,12.000000,13.000000
max,85.000000,6951.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,1592.000000,1584.000000

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 129880 entries, 0 to 129879
Data columns (total 22 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   satisfaction                       129880 non-null  object
 1   Customer Type                      129880 non-null  object
 2   Age                                129880 non-null  int64
 3   Type of Travel                     129880 non-null  object
 4   Class                              129880 non-null  object
 5   Flight Distance                    129880 non-null  int64
 6   Seat comfort                       129880 non-null  int64
 7   Departure/Arrival time convenient  129880 non-null  int64
 8   Food and drink                     129880 non-null  int64
 9   Gate location                      129880 non-null  int64
 10  Inflight wifi service              129880 non-null  int64
 11  Inflight entertainment             129880 non-null  int64
 12  Online support                     129880 non-null  int64
 13  Ease of Online booking             129880 non-null  int64
 14  On-board service                   129880 non-null  int64
 15  Leg room service                   129880 non-null  int64
 16  Baggage handling                   129880 non-null  int64
 17  Checkin service                    129880 non-null  int64
 18  Cleanliness                        129880 non-null  int64
 19  Online boarding                    129880 non-null  int64
 20  Departure Delay in Minutes         129880 non-null  int64
 21  Arrival Delay in Minutes           129487 non-null  float64
dtypes: float64(1), int64(17), object(4)
memory usage: 21.8+ MB

In [59]:
df.groupby(["satisfaction"]).count()

,Customer Type,Age,Type of Travel,Class,Flight Distance,Seat comfort,Departure/Arrival time convenient,Food and drink,Gate location,Inflight wifi service,Inflight entertainment,Online support,Ease of Online booking,On-board service,Leg room service,Baggage handling,Checkin service,Cleanliness,Online boarding,Departure Delay in Minutes,Arrival Delay in Minutes
satisfaction,,,,,,,,,,,,,,,,,,,,,
dissatisfied,58793,58793,58793,58793,58793,58793,58793,58793,58793,58793,58793,58793,58793,58793,58793,58793,58793,58793,58793,58793,58605
satisfied,71087,71087,71087,71087,71087,71087,71087,71087,71087,71087,71087,71087,71087,71087,71087,71087,71087,71087,71087,71087,70882

**Total satisfied customer 71087**

In [ ]:
df.groupby(["satisfaction"]).count()

In [61]:
df.groupby(by=["Customer Type"]).count()

,satisfaction,Age,Type of Travel,Class,Flight Distance,Seat comfort,Departure/Arrival time convenient,Food and drink,Gate location,Inflight wifi service,Inflight entertainment,Online support,Ease of Online booking,On-board service,Leg room service,Baggage handling,Checkin service,Cleanliness,Online boarding,Departure Delay in Minutes,Arrival Delay in Minutes
Customer Type,,,,,,,,,,,,,,,,,,,,,
Loyal Customer,106100,106100,106100,106100,106100,106100,106100,106100,106100,106100,106100,106100,106100,106100,106100,106100,106100,106100,106100,106100,105773
disloyal Customer,23780,23780,23780,23780,23780,23780,23780,23780,23780,23780,23780,23780,23780,23780,23780,23780,23780,23780,23780,23780,23714

**Total Loyal Customer 106100**
**Total Disloyal Customer 23780**

In [63]:
df.groupby(by=["Class",'satisfaction']).count()

                       Customer Type    Age  Type of Travel  Flight Distance  \
Class    satisfaction
Business dissatisfied          18065  18065           18065            18065
         satisfied             44095  44095           44095            44095
Eco      dissatisfied          35336  35336           35336            35336
         satisfied             22973  22973           22973            22973
Eco Plus dissatisfied           5392   5392            5392             5392
         satisfied              4019   4019            4019             4019

                       Seat comfort  Departure/Arrival time convenient  \
Class    satisfaction
Business dissatisfied         18065                              18065
         satisfied            44095                              44095
Eco      dissatisfied         35336                              35336
         satisfied            22973                              22973
Eco Plus dissatisfied          5392                               5392
         satisfied             4019                               4019

                       Food and drink  Gate location  Inflight wifi service  \
Class    satisfaction
Business dissatisfied           18065          18065                  18065
         satisfied              44095          44095                  44095
Eco      dissatisfied           35336          35336                  35336
         satisfied              22973          22973                  22973
Eco Plus dissatisfied            5392           5392                   5392
         satisfied               4019           4019                   4019

                       Inflight entertainment  Online support  \
Class    satisfaction
Business dissatisfied                   18065           18065
         satisfied                      44095           44095
Eco      dissatisfied                   35336           35336
         satisfied                      22973           22973
Eco Plus dissatisfied                    5392            5392
         satisfied                       4019            4019

                       Ease of Online booking  On-board service  \
Class    satisfaction
Business dissatisfied                   18065             18065
         satisfied                      44095             44095
Eco      dissatisfied                   35336             35336
         satisfied                      22973             22973
Eco Plus dissatisfied                    5392              5392
         satisfied                       4019              4019

                       Leg room service  Baggage handling  Checkin service  \
Class    satisfaction
Business dissatisfied             18065             18065            18065
         satisfied                44095             44095            44095
Eco      dissatisfied             35336             35336            35336
         satisfied                22973             22973            22973
Eco Plus dissatisfied              5392              5392             5392
         satisfied                 4019              4019             4019

                       Cleanliness  Online boarding  \
Class    satisfaction
Business dissatisfied        18065            18065
         satisfied           44095            44095
Eco      dissatisfied        35336            35336
         satisfied           22973            22973
Eco Plus dissatisfied         5392             5392
         satisfied            4019             4019

                       Departure Delay in Minutes  Arrival Delay in Minutes
Class    satisfaction
Business dissatisfied                       18065                     18013
         satisfied                          44095                     43977
Eco      dissatisfied                       35336                     35219
         satisfied                          22973                     22898
Eco Plus dissatisfied                        5392                      5373
         satisfied                           4019                      4007